<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>ObsBatteryGuard.Guard</AssemblyName>
    <ApplicationIcon>..\ObsBatteryGuard.App\Assets\app.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ObsBatteryGuard.Core\ObsBatteryGuard.Core.csproj" />
  </ItemGroup>
</Project>
